I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 423, in script
    Diary Entry "I’m really glad Raka opened up to me about their past partners and shared so many of their stories with me. Their confidence is sooo attractive. Like, they just know what they want and how to get it."
Exception: Sayer 'Diary' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 423, in script
    Diary Entry "I’m really glad Raka opened up to me about their past partners and shared so many of their stories with me. Their confidence is sooo attractive. Like, they just know what they want and how to get it."
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Diary' is not defined.

macOS-13.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
lovehurts 1.0
Sun May 12 15:59:11 2024
