I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 918, in script
    show langur worried heind deer:
Exception: Image 'langur worried' does not accept attributes 'heind deer'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 918, in script
    show langur worried heind deer:
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/display/core.py", line 499, in _duplicate
    args.extraneous()
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/display/core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'langur worried' does not accept attributes 'heind deer'.

macOS-13.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
lovehurts 1.0
Sun Oct 15 19:54:33 2023
