I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "game/mobile.rpy", line 15, in execute_default
    default phonebackground = 1
Exception: store.phonebackground is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/exports.py", line 3982, in execute_default_statement
    i.execute_default(start)
  File "game/mobile.rpy", line 15, in execute_default
    default phonebackground = 1
Exception: store.phonebackground is being given a default a second time.

macOS-13.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
lovehurts 1.0
Mon Mar 25 21:05:22 2024
